name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    env:
      SIZE_LIMIT: 15.0KB
      CARGO_TERM_COLOR: never
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Install Rust
      uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de # master
      with:
        toolchain: stable
        components: clippy, rustfmt
    - name: Cache cargo and target
      uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
    - name: Run tests
      run: make tests
    - name: Check crate package size
      run: cargo run -- diet --dry-run --package-size-limit ${{ env.SIZE_LIMIT }}
    - name: Check crate package size (with install action)
      run: cargo install cargo-diet --locked
    - name: Check crate package size (with latest binary)
      run: |
        curl -LSfs https://raw.githubusercontent.com/the-lean-crate/cargo-diet/master/ci/install.sh | \
            sh -s -- --git the-lean-crate/cargo-diet --target x86_64-unknown-linux-musl --force


        cargo diet --dry-run --package-size-limit ${{ env.SIZE_LIMIT }}
    - name: fmt
      run: cargo fmt --all -- --check
    - name: clippy
      run: cargo clippy --all-targets -- -D warnings

  zizmor:
    name: zizmor
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@cc914d7f3750a2d13d75c7f184a1060aa0e9d482 # v0.6.4
