name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    env:
      SIZE_LIMIT: 11KB
      CARGO_TERM_COLOR: never
    steps:
    - uses: actions/checkout@v7
      with:
        persist-credentials: false
    - name: Install Rust
      uses: dtolnay/rust-toolchain@fa04a1451ff1842e2626ccb99004d0195b455a88 # master
      with:
        toolchain: stable
        components: clippy, rustfmt
    - name: Cache cargo and target
      uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
    - name: Run tests
      run: make tests
    - name: Check crate package size
      run: cargo run -- diet --dry-run --package-size-limit ${{ env.SIZE_LIMIT }}
    - name: Check crate package size (with install action)
      run: cargo install cargo-diet --locked
    - name: Check crate package size (with latest binary)
      run: |
        curl -LSfs https://raw.githubusercontent.com/the-lean-crate/cargo-diet/master/ci/install.sh | \
            sh -s -- --git the-lean-crate/cargo-diet --target x86_64-unknown-linux-musl --force


        cargo diet --dry-run --package-size-limit ${{ env.SIZE_LIMIT }}
    - name: fmt
      run: cargo fmt --all -- --check
    - name: clippy
      run: cargo clippy --all-targets -- -D warnings
